### ISSUE TITLE
how to use the raw data?

### ISSUE THREAD

**Issue by wwHwo** [hellopipu/RefineGAN#1]
thx for your pytorch implementation of RefineGAN!!!  
Do you know how to deal with the raw data?  The raw K-space data is .nii file, should i read those and save as .jpg?
thx for your help!!

**Comment by hellopipu** [comment]
You should read the data directly from .nii file and then process it.

Saving as .jpg is not recommended. K-space data is complex-valued data. If you save as a jpg file, the imaginary part of the k-space is lost, and JPG is a lossy compression of the real part.

I'm using a .png dataset in this repo just to keep it the same as the original repo, but keeping medical data in .jpg/.png files is not recommended.
